on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

name: lint

jobs:
  lint:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v14.4
        with:
          since_last_remote_commit: 'true'

      - name: get_modified_files
        id: diff
        run: |
          git config diff.renameLimit 99000
          git fetch origin $GITHUB_BASE_REF --depth=1
          touch files.txt
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo $file >> files.txt
          done

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - name: Setup lintr
        run: install.packages('lintr')
        shell: Rscript {0}

      - name: Lint
        run: |
          files <- read.table('files.txt')
          print(files)
          for (file in files) {
            lintr::lint(
             file,
             linters = lintr::linters_with_defaults(
               line_length_linter=NULL,
               object_name_linter=NULL,
               cyclocomp_linter=NULL,
               seq_linter=NULL,
               object_length_linter=NULL,
               vector_logic_linter=NULL
             )
          )
          }
        shell: Rscript {0}
        env:
          LINTR_ERROR_ON_LINT: true