on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

name: lint

jobs:
  lint:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - name: get diff
        run: |
          git fetch origin main
          git diff --name-only  --diff-filter=ACMRTUXB main | grep  -E "(.r$|.R$)" > files.txt

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - name: Setup lintr
        run: install.packages('lintr')
        shell: Rscript {0}

      - name: Lint
        run: |
          files <- read.table('files.txt')
          print(files)
          for (file in files) {
            lintr::lint(
             file,
             linters = lintr::linters_with_defaults(
               line_length_linter=NULL,
               object_name_linter=NULL,
               cyclocomp_linter=NULL,
               seq_linter=NULL,
               object_length_linter=NULL,
               vector_logic_linter=NULL
             )
          )
          }
        shell: Rscript {0}
        env:
          LINTR_ERROR_ON_LINT: true